spring:
  data:
    mongodb:
      host: 192.168.6.128
      port: 27017
      database: mall
      auto-index-creation: true
      authentication-database: admin
      username: admin
      password: "123456"

