spring:
  data:
    redis:
      port: 6379
      host: localhost
      lettuce:
        pool:
          max-idle: 16
          max-active: 32
          min-idle: 8
      database: 1
    mongodb:
      host: 192.168.6.128
      port: 27017
      database: mall
      auto-index-creation: true
      authentication-database: admin
      username: admin
      password: "123456"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # 开启消息确认机制
    publisher-confirm-type: correlated
    # 开启消息返回机制
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: auto  # 改为自动确认
        prefetch: 1
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
# 自定义配置
app:
  rabbitmq:
    # 主题交换机名称
    topic-exchange: topic.exchange
    # 队列名称
    order-queue: order.queue
    user-queue: user.queue
    # 路由键
    order-routing-key: order.*
    user-routing-key: user.*
    all-routing-key: "#"
